"""Allow non recurring tasks

Revision ID: 4cd5e01433d2
Revises: 6bc15c0083de
Create Date: 2026-08-21 09:56:01.050486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd5e01433d2'
down_revision: Union[str, Sequence[str], None] = '6bc15c0083de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'repeat_type',
               existing_type=postgresql.ENUM('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'SEMESTERLY', 'TWICE_A_YEAR', 'YEARLY', name='repeat_type'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'repeat_type',
               existing_type=postgresql.ENUM('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'SEMESTERLY', 'TWICE_A_YEAR', 'YEARLY', name='repeat_type'),
               nullable=False)
    # ### end Alembic commands ###
