"""Add active status to households and events

Revision ID: 6bc15c0083de
Revises: 9a521ae41c5b
Create Date: 2026-08-17 15:45:03.899882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc15c0083de'
down_revision: Union[str, Sequence[str], None] = '9a521ae41c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('households', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('households', 'is_active')
    op.drop_column('events', 'is_active')
    # ### end Alembic commands ###
