"""Add awards points to tasks

Revision ID: 7a3001d33d34
Revises: bbc5e41ddec7
Create Date: 2026-08-24 10:13:13.692855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3001d33d34'
down_revision: Union[str, Sequence[str], None] = 'bbc5e41ddec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('awards_points', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'awards_points')
    # ### end Alembic commands ###
