"""Allow personal tasks without category or room

Revision ID: 9a521ae41c5b
Revises: 5580476509c9
Create Date: 2026-08-07 11:27:54.303224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a521ae41c5b'
down_revision: Union[str, Sequence[str], None] = '5580476509c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
